[package]
name = "mariochao/purple-coins-challenge"
version = "0.0.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
BadgeUtil = "mariochao/badge-util@^0.0.0"
